// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 const sidebars = {
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'NeoEdge NG4500 Series',
      items: [
        { type: 'autogenerated', dirName: '1-NeoEdge NG4500 Series' },
      ],
    },
    {
      type: 'category',
      label: 'NeoEyes NE101 Series',
      items: [
        { type: 'autogenerated', dirName: '2-NeoEyes NE101 Series' },
      ],
    },
    {
      type: 'category',
      label: 'Hardware Dev Resources',
      items: [
        { type: 'autogenerated', dirName: '3-Hardware Dev Resources' },
      ],
    },
  ],
};

export default sidebars;